[package]
name = "todo"
description = "A complete todo app built with schnellui"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "todo"
path = "src/main.rs"

[dependencies]
schnellui.workspace = true
schnellui-testing.workspace = true
clap.workspace = true
strum.workspace = true
